sudo: required
language: bash
services:
  - docker

before_install:
  - docker build -t libyui-rake-image .
script:
  # the "libyui-travis" script is included in the base libyui/devel image
  # see https://github.com/libyui/docker-devel/blob/master/libyui-travis
  - docker run -it libyui-rake-image rubocop
  - docker run -it libyui-rake-image libyui-travis
